version: '3'

services:
  # sipi using default (production-like) configuration with additional routes for testing
  sipi:
    image: daschswiss/knora-sipi:latest
    container_name: sipi
    ports:
      - "1024:1024"
    volumes:
      - $PWD/config:/sipi/config
      - $PWD/scripts:/sipi/scripts
      - /tmp:/tmp
      - $HOME:$HOME
      - $PWD/images:/sipi/images
      - $PWD/server:/sipi/server
    extra_hosts:
      - api:${DOCKERHOST}
    restart: unless-stopped
    environment:
      - SIPI_EXTERNAL_PROTOCOL=http
      - SIPI_EXTERNAL_HOSTNAME=0.0.0.0
      - SIPI_EXTERNAL_PORT=1024
    command: --config=/sipi/config/sipi.knora-docker-config.lua

  # sipi using configuration which disables authentication
  sipi-no-auth:
    image: daschswiss/knora-sipi:latest
    container_name: sipi-no-auth
    ports:
      - "1024:1024"
    volumes:
      - $PWD/config:/sipi/config
      - $PWD/scripts:/sipi/scripts
      - /tmp:/tmp
      - $HOME:$HOME
      - $PWD/images:/sipi/images
      - $PWD/server:/sipi/server
    extra_hosts:
      - api:${DOCKERHOST}
    restart: unless-stopped
    environment:
      - SIPI_EXTERNAL_PROTOCOL=http
      - SIPI_EXTERNAL_HOSTNAME=0.0.0.0
      - SIPI_EXTERNAL_PORT=1024
    command: --config=/sipi/config/sipi.knora-docker-no-auth-config.lua
