name: CI

on:
  push:
  release:
    types: [published]

jobs:
  compile:
    name: Build Everything
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 15
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+02:00"
      - name: use daily bazel disk cache
        uses: actions/cache@v2
        with:
          path: ~/.bazel_disk_cache
          key: ${{ runner.OS }}-bazel_disk_cache-${{ steps.current-time.outputs.formattedTime }}
      - name: setup java version
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: install requirements
        run: sudo apt-get install ca-certificates-java expect
      - name: run build everything
        run: bazel build //...
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build and Test
        run: sbt -v +test
      - name: Cleanup before cache
        shell: bash
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true

# ------------------------------------------
# ------------------------------------------
# Test client-test-data 
  client-test-data-tests:
    name: Test client-test-data 
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 15
      - name: get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+02:00"
      - name: use daily bazel disk cache
        uses: actions/cache@v2
        with:
          path: ~/.bazel_disk_cache
          key: ${{ runner.OS }}-bazel_disk_cache-${{ steps.current-time.outputs.formattedTime }}
      - name: setup java version
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: install requirements
        run: sudo apt-get install ca-certificates-java expect redis-tools unzip
      - name: generate api-client-test-data
        run: make client-test-data

# ------------------------------------------
# ------------------------------------------

  api-unit-tests:
    name: API Unit Tests
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 15
      - name: get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+02:00"
      - name: use daily bazel disk cache
        uses: actions/cache@v2
        with:
          path: ~/.bazel_disk_cache
          key: ${{ runner.OS }}-bazel_disk_cache-${{ steps.current-time.outputs.formattedTime }}
      - name: setup java version
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: install requirements
        run: sudo apt-get install ca-certificates-java expect
      - name: use daily bazel disk cache
        uses: actions/cache@v2
        with:
          path: ~/.bazel_disk_cache
          key: ${{ runner.OS }}-bazel_disk_cache-${{ steps.date.outputs.date }} }}
      - name: run API unit tests
        run: make test-unit

  api-e2e-tests:
    name: API E2E Tests
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 15
      - name: get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+02:00"
      - name: use daily bazel disk cache
        uses: actions/cache@v2
        with:
          path: ~/.bazel_disk_cache
          key: ${{ runner.OS }}-bazel_disk_cache-${{ steps.current-time.outputs.formattedTime }}
      - name: setup java version
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: install requirements
        run: sudo apt-get install ca-certificates-java expect redis-tools unzip
      - name: run API E2E tests
        run: make test-e2e

  api-integration-tests:
    name: API Integration Tests
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 15
      - name: get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+02:00"
      - name: use daily bazel disk cache
        uses: actions/cache@v2
        with:
          path: ~/.bazel_disk_cache
          key: ${{ runner.OS }}-bazel_disk_cache-${{ steps.current-time.outputs.formattedTime }}
      - name: setup java version
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: Install dependencies
        run: |
          sudo apt-get install ca-certificates-java expect
      - name: run API integration tests
        run: |
          make test-docker
          make test-it

  upgrade-integration-tests:
    name: Upgrade Integration Tests
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 15
      - name: get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+02:00"
      - name: use daily bazel disk cache
        uses: actions/cache@v2
        with:
          path: ~/.bazel_disk_cache
          key: ${{ runner.OS }}-bazel_disk_cache-${{ steps.current-time.outputs.formattedTime }}
      - name: setup java version
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: Install dependencies
        run: |
          sudo apt-get install ca-certificates-java expect
      - name: test repository upgrade
        run: make test-repository-upgrade

  docs-build-test:
    name: Build Docs Testrun
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          npm install --global typedoc
          sudo apt-get install graphviz
      - name: run docs build
        run: make docs-build

  release-please:
    name: Prepare next release
    runs-on: ubuntu-latest
    # Automate releases with Conventional Commit Messages as Pull Requests are merged into "main" branch
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: simple
          package-name: dsp-api
          changelog-types: '[
            {"type": "feat", "section": "Enhancements", "hidden": false },
            {"type": "fix", "section": "Bug Fixes", "hidden": false },
            {"type": "build", "section": "Maintenance", "hidden": false },
            {"type": "chore", "section": "Maintenance", "hidden": false },
            {"type": "refactor", "section": "Maintenance", "hidden": false },
            {"type": "docs", "section": "Documentation", "hidden": false }
          ]'

  # publish only on release
  publish:
    name: Publish (on release only)
    needs: [
      api-unit-tests,
      api-e2e-tests,
      api-integration-tests,
      client-test-data-tests,
      upgrade-integration-tests,
      docs-build-test
    ]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+02:00"
      - name: use daily bazel disk cache
        uses: actions/cache@v2
        with:
          path: ~/.bazel_disk_cache
          key: ${{ runner.OS }}-bazel_disk_cache-${{ steps.current-time.outputs.formattedTime }}
      - name: setup java version
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: install requirements
        run: sudo apt-get install ca-certificates-java expect redis-tools unzip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          npm install --global typedoc
          sudo apt-get install graphviz
      - name: generate api-client-test-data
        run: make client-test-data
      - name: add api-client-test-data to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: client-test-data.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: build and publish all images to Dockerhub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          make docker-publish

  # google chat notification about release
  notification:
    name: Google chat notification about release and published version
    needs: [publish]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: send notification to google chat room "DSP releases"
        uses: lakto/google-chat-action@main
        with:
          url: ${{ secrets.GOOGLE_CHAT_DSP_RELEASES_WEBHOOK_URL }}

  # deploy documentation only on release
  deploy-docs:
    name: Deploy docs (on release only)
    needs: [
      docs-build-test
    ]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          npm install --global typedoc
          sudo apt-get install graphviz
      - name: deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CUSTOM_DOMAIN: docs-api.dasch.swiss
          REQUIREMENTS: docs/requirements.txt
